name: aa_wallet
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+101

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
#  # https://pub.dev/packages/decimal
#  decimal: ^1.5.0
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.2.6
  # getx 状态管理框架 https://pub.dev/packages/get  搭配手脚架使用 https://github.com/jonataslaw/get_cli
  get: ^4.6.5

  # 复制粘贴 https://pub.dev/packages/clipboard
  clipboard: ^0.1.3
  # 用于生成copyWith扩展的注释  https://pub.dev/packages/copy_with_extension
  copy_with_extension: ^5.0.4
  # https://pub.dev/packages/encrypt
  encrypt: ^5.0.3
#  # 国际化 https://pub.dev/packages/intl
#  intl: ^0.17.0
  # json映射 https://pub.flutter-io.cn/packages/json_serializable
  json_serializable: ^6.8.0
  # json映射 https://pub.flutter-io.cn/packages/json_annotation
  json_annotation: ^4.9.0
  # 手机权限 https://pub.dev/packages/permission_handler
  permission_handler: ^11.3.1
#  # 状态管理 https://pub.dev/packages/provider
#  provider: ^6.0.1
  # 实用的dart转换工具 https://pub.dev/packages/quiver
  quiver: ^3.2.1
  # 日志控制 https://pub.dev/packages/loggy
  loggy: ^2.0.3
#  # 数据库 https://pub.flutter-io.cn/packages/sqflite
#  sqflite: ^2.0.0+4
  # 数据库 https://pub.flutter-io.cn/packages/moor_flutter
  moor_flutter: ^4.1.0

  # Network
  # dio网络请求框架 https://pub.dev/packages/dio
  dio: ^5.4.3+1
  # dio网络转换 https://pub.dev/packages/dio_flutter_transformer
  #  dio_flutter_transformer: ^3.0.2
  # 映射dio返回 https://pub.dev/packages/retrofit
  retrofit: ^4.1.0

  # UI
  # 动画实用类 https://pub.dev/packages/animations
  animations: ^2.0.11
  # 全局toast https://pub.dev/packages/bot_toast
  bot_toast: ^4.0.1
  # 消息小圈圈 https://pub.dev/packages/badges
  #  badges: ^2.0.1
  # 拓展的image控件 https://pub.dev/packages/image
  image: ^4.1.7
  # 图片编辑 https://pub.dev/packages/image_editor
  image_editor: ^1.5.1
  # 强大的图片拓展工具 https://pub.dev/packages/extended_image
  extended_image: ^8.2.0
  # 特殊的TextSpan https://pub.dev/packages/extended_text
  extended_text: ^13.0.0
  # 一个强大的瀑布流布局UI控件 https://pub.dev/packages/flutter_staggered_grid_view
  # flutter_staggered_grid_view: ^0.4.1
  # 电商会比较多用的UI菜单 https://pub.dev/packages/gzx_dropdown_menu
  #  gzx_dropdown_menu: ^3.1.0
  # 下拉刷新上拉加载 https://pub.dev/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  # 小动画控件 https://pub.dev/packages/sa_stateless_animation
  #  sa_stateless_animation: ^1.2.0
  # https://pub.dev/packages/webview_flutter
#  webview_flutter: ^3.0.0
  # 微信选择照片控件 https://pub.dev/packages/wechat_assets_picker
  wechat_assets_picker: ^9.0.3
  # 微信照片 https://pub.dev/packages/wechat_camera_picker
  wechat_camera_picker: ^4.2.2

  # https://pub.dev/packages/scrollable_positioned_list
  #  scrollable_positioned_list: ^0.2.0-nullsafety.0
  # https://pub.dev/packages/video_player
  #  video_player: ^2.1.14
  # 指示器 https://pub.dev/packages/dots_indicator
  dots_indicator: ^3.0.0

  # Utility
  #  # 异步控制 https://pub.dev/packages/async
  #  async: ^2.8.2
  # 算法 https://pub.dev/packages/collection
  collection: ^1.18.0
  # 常用工具类库 https://pub.dev/packages/flustars
  flustars: ^2.0.1
  # 时间选择器 https://pub.dev/packages/flutter_picker
  flutter_picker: ^2.1.0
  # 获取系统信息类 https://pub.dev/packages/package_info_plus
  package_info_plus: ^8.0.0
  # 路径 https://pub.dev/packages/path
  path: ^1.9.0
#  # 文件路径 https://pub.dev/packages/path_provider
#  path_provider: ^2.0.8
  # 启动图片 https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.4.0
  # app icon 生成图片 https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
  # 本地缓存 https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.3
  # html解读 https://pub.dev/packages/flutter_html
  flutter_html: ^3.0.0-beta.2
  # 二维码扫描 https://pub.dev/packages/qr_code_scanner   没有WEB
  qr_code_scanner: ^1.0.1
  # 二维码控件 https://pub.dev/packages/qr_flutter
  qr_flutter: ^4.1.0
  # 加載動畫 https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: ^5.2.1


  ########################################################################
  ####以上的插件，尽量不要更换；因为可能core会用到。您想更换的在下面添加您使用的####
  ########################################################################

  #####区块链需要插件
  # web3dart https://pub.dev/packages/web3dart
  web3dart: ^2.7.3
  # bip39 https://pub.dev/packages/bip39
  bip39: ^1.0.6
  # bip32 https://pub.dev/packages/bip32
  bip32: ^2.0.0
  # http https://pub.dev/packages/http
  http: ^1.2.1
  # hex https://pub.dev/packages/hex
  hex: ^0.2.0
  # aes 加解密 https://pub.dev/packages/aes_ecb_pkcs5_flutter
  aes_ecb_pkcs5_flutter: ^0.1.2
  #####区块链需要插件

  # 保存图片 https://pub.dev/packages/image_gallery_saver   没有WEB
  image_gallery_saver: ^2.0.3
#  # bitcoin_flutter https://pub.dev/packages/bitcoin_flutter
#  bitcoin_flutter: ^2.0.2
  # 滑动删除 https://pub.dev/packages/flutter_slidable
  flutter_slidable: ^3.1.0
  #  #app更新
  app_upgrade:
    git:
      url: https://gitee.com/willzh/app_upgrade.git


#dependency_overrides:
#  # https://pub.dev/packages/decimal
#  decimal: 1.5.0
#  photo_manager: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

  # https://pub.flutter-io.cn/packages/build_runner
  build_runner: ^2.4.9
  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: ^8.1.0
#  # https://pub.dev/packages/moor_generator
#  moor_generator: ^4.6.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/language.json
    - assets/images/ic_aaa.png
    - assets/images/ic_aaa_select.png
    - assets/images/ic_aac.png
    - assets/images/ic_asdt.png
    - assets/images/ic_btc.png
    - assets/images/ic_btc_select.png
    - assets/images/ic_bzz.png
    - assets/images/ic_choose.png
    - assets/images/ic_choose_lang.png
    - assets/images/ic_collection.png
    - assets/images/ic_copy.png
    - assets/images/ic_copy_blue.png
    - assets/images/ic_creat_wallet.png
    - assets/images/ic_edit.png
    - assets/images/ic_en_us.png
    - assets/images/ic_eth.png
    - assets/images/ic_eth_select.png
    - assets/images/ic_img.png
    - assets/images/ic_main.png
    - assets/images/ic_mnemonic.png
    - assets/images/ic_more.png
    - assets/images/ic_no_data.png
    - assets/images/ic_no_screenshots.png
    - assets/images/ic_private_key.png
    - assets/images/ic_profile.png
    - assets/images/ic_profile_selcet.png
    - assets/images/ic_qr_code_bg.png
    - assets/images/ic_recover_wallet.png
    - assets/images/ic_save.png
    - assets/images/ic_scan.png
    - assets/images/ic_tips.png
    - assets/images/ic_transfer.png
    - assets/images/ic_trx.png
    - assets/images/ic_update_record.png
    - assets/images/ic_usdt.png
    - assets/images/ic_wallet.png
    - assets/images/ic_wallet_all.png
    - assets/images/ic_wallet_all_select.png
    - assets/images/ic_wallet_management.png
    - assets/images/ic_wallet_select.png
    - assets/images/ic_zh_hans.png
    - assets/images/icon.png
    - assets/images/splash.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
          nullable: true
      moor_generator:
        options:
          compact_query_methods: true

# https://plugins.jetbrains.com/plugin/13666-flutter-intl
# https://pub.dev/packages/intl_utils
flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: AppS # Optional. Sets the name for the generated localization class. Default: S
#  main_locale: zh_Hans # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
#  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system.
#  localizely: # Optional settings if you use Localizely platform. Read more: https://localizely.com/flutter-localization-workflow
#    project_id: # Get it from the https://app.localizely.com/projects page.
#    branch: # Get it from the “Branches” page on the Localizely platform, in case branching is enabled and you want to use a non-main branch.
#    upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
#    upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
#    ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
#生成logo图标  命令行： flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

#生成启动背景图  命令行：flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/splash.png
  color: "#FFFFFF"
  android: true
  android_disable_fullscreen: true
