// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
class CoreRes {
  const CoreRes._();
  static const String assets_emoji_input_btn_backspace_png =
      'assets/images/emoji_input_btn_backspace.png';

  static const String assets_emoji_input_btn_backspace_disable_png =
      'assets/images/emoji_input_btn_backspace_disable.png';

  static const String assets_error_cloud_png = 'assets/images/error_cloud.png';

  static const String assets_ic_navigation_png = 'assets/images/ic_navigation.png';

  static const String assets_ic_poi_picked_png = 'assets/images/ic_poi_picked.png';

  // static const String assets_sensitive_words_txt = 'assets/images/sensitive_words.txt';

  static const String assets_toast_icon_done_png = 'assets/images/toast_icon_done.png';

  static const String assets_toast_icon_error_png =
      'assets/images/toast_icon_error.png';
}